openapi: 3.0.3
info:
  title: PROG3 - TD2
  description: PROG3 - TD2
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /teams:
    get:
      tags:
        - Teams
      summary: get all teams
      operationId: getTeams
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error

    post:
      tags:
        - Teams
      summary: create new team
      operationId: createTeam
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateTeam'
      responses:
        '200':
          description: List of teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error

    put:
      tags:
        - Teams
      summary: update teams
      operationId: updateTeams
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/UpdateTeam'
      responses:
        '200':
          description: List of updated teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '500':
          description: Internal server error

  /players:
    get:
      tags:
        - Players
      summary: get all players
      operationId: getPlayers
      responses:
        '200':
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error

    post:
      tags:
        - Players
      summary: create new player
      operationId: createPlayer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreatePlayer'
      responses:
        '200':
          description: List of created players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error

    put:
      tags:
        - Players
      summary: update players
      operationId: updatePlayers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Player'
      responses:
        '200':
          description: List of updated players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error

  /sponsors:
    get:
      tags:
        - Sponsors
      summary: get all sponsors
      operationId: getSponsors
      responses:
        '200':
          description: List of sponsors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sponsor'
        '500':
          description: Internal server error

    post:
      tags:
        - Sponsors
      summary: create new sponsor
      operationId: createSponsor
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreatePlayer'
      responses:
        '200':
          description: List of created players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Player'
        '500':
          description: Internal server error

    put:
      tags:
        - Sponsors
      summary: update sponsors
      operationId: updateSponsors
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Sponsor'
      responses:
        '200':
          description: List of created sponsors
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Sponsor'

  /matches:
    get:
      tags:
        - Matches
      summary: get all matches
      operationId: getMatches
      responses:
        '200':
          description: List of matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error

    post:
      tags:
        - Matches
      summary: create new matche
      operationId: createMatches
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateMatch'
      responses:
        '200':
          description: List of created players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'
        '500':
          description: Internal server error

    put:
      tags:
        - Matches
      summary: update matches
      operationId: updateMatches
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Match'
      responses:
        '200':
          description: List of created matches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Match'

components:
  schemas:
    CreateSponsor:
      type: object
      properties:
        name:
          type: string
    Sponsor:
      type: object
      properties:
        id:
          type: string
      allOf:
        - $ref: '#/components/schemas/CreateSponsor'

    CreatePlayer:
      type: object
      properties:
        name:
          type: string
        isGuardian:
          type: boolean
    Player:
      properties:
        id:
          type: integer
        name:
          type: string
        isGuardian:
          type: boolean

    CreateTeam:
      type: object
      properties:
          name:
            type: string
    UpdateTeam:
      type: object
      properties:
        id:
          type: integer
        sponsors:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Sponsor'
      allOf:
        - $ref: '#/components/schemas/CreateTeam'
    Team:
      type: object
      properties:
        id:
          type: integer
        players:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Player'
        sponsors:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/Sponsor'
      allOf:
        - $ref: '#/components/schemas/CreateTeam'

    CreateMatch:
      type: object
      properties:
        homeTeam:
          type: object
          allOf:
            - $ref: '#/components/schemas/Team'
        awayTeam:
          type: object
          allOf:
            - $ref: '#/components/schemas/Team'
        datetime:
          type: string
          format: date
    Match:
      type: object
      properties:
        id:
          type: integer
        datetime:
          type: string
          format: datetime
        stadium:
          type: string
        teamHome:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'
        teamAway:
          allOf:
            - $ref: '#/components/schemas/PlayedTeam'

    PlayedTeam:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        goals:
          type: string
        scorers:
          type: object
          properties:
            player:
              $ref: '#/components/schemas/Player'
            isOG:
              type: boolean
            scoreTime:
              type: integer

    Scorers:
      type: object
      properties:
        player:
          $ref: '#/components/schemas/Player'
        isOG:
          type: boolean
        scoreTime:
          type: integer